---
Name: swiftypesearch
After: 'framework/*','cms/*','searchlist/*'
---
LeftAndMain:
  extensions:
    - Marcz\Swiftype\SwiftypeAdminExtension
Marcz\Search\Config:
  clients:
    - name: 'Swiftype'
      write: true
      delete: true
      export: 'json'
      class: 'Marcz\Swiftype\SwiftypeClient'
Marcz\Search\Processor\Exporter:
  extensions:
    - Marcz\Swiftype\Extensions\Exporter
SiteConfig:
  extensions:
    - Marcz\Swiftype\Extensions\SiteConfig